## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeVector <- function(x = numeric()) {
        m <- NULL
        set <- function(y) {
                x <<- y    ##x is a variable which stores value of y
                m <<- NULL ##m stores Null
        }
        get <- function() x ##get stores valuegenerated by function()x
        setmean <- function(mean) m <<- mean
        getmean <- function() m
        list(set = set, get = get,
             setmean = setmean,
             getmean = getmean)
}


## Write a short comment describing this function

cachemean <- function(x, ...) {
        m <- x$getmean()##m stores the value getmean attribute
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- mean(data, ...)
        x$setmean(m)
        m
}
